/* FOR LOAD FILES */
/*
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE LOB_OBJ';
  EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/
*/

CREATE TABLE LOB_OBJ (
  ID            NUMBER(5),
  NAME_CONTENT  VARCHAR2(100),
  LANG_CONTENT  VARCHAR2(2),
  CATEGORY_CONTENT VARCHAR2(100),
  SHORT_CONTENT CLOB,
  CLOB_CONTENT  CLOB,
  USER_NAME     VARCHAR2(30) DEFAULT USER,
  USER_DATE     DATE DEFAULT SYSDATE 
);
