WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK
CONN &3/&4@&5 AS SYSDBA

-------- CREATE USER  ------------------------------------
-- create the user 
CREATE USER &1
  IDENTIFIED BY &2
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT;

-- alter user
ALTER USER &1 QUOTA UNLIMITED ON USERS;  
 
-- grant/revoke system privileges 
GRANT GLOBAL QUERY REWRITE TO &1;
GRANT SELECT ANY TABLE TO &1;
GRANT UNLIMITED TABLESPACE TO &1;
grant execute on DBMS_CRYPTO to &1;

-- for PL/sql developer------------------
GRANT SELECT ON SYS.V_$SESSION TO &1;
GRANT SELECT ON SYS.V_$SESSTAT TO &1;
GRANT SELECT ON SYS.V_$STATNAME TO &1;
GRANT SELECT ON SYS.USER$ TO &1;
GRANT SELECT ON DBA_ROLE_PRIVS TO &1;
GRANT SELECT ON DBA_USERS TO &1;

------------------------------------------

GRANT CREATE TABLE TO &1;
GRANT CREATE SESSION TO &1;
GRANT CREATE PROCEDURE TO &1;
GRANT CREATE TRIGGER TO &1;
GRANT CREATE VIEW TO &1;
GRANT CREATE SEQUENCE TO &1;
GRANT CREATE VIEW TO &1;
GRANT CREATE ROLE TO &1;
GRANT CREATE MATERIALIZED VIEW TO &1;

GRANT DELETE ANY TABLE TO &1;
GRANT DROP ANY TABLE TO &1;
GRANT DROP ANY PROCEDURE TO &1;
GRANT DROP ANY TRIGGER TO &1;
GRANT DROP ANY VIEW TO &1;
GRANT DROP ANY ROLE TO &1;
GRANT DROP ANY SYNONYM TO &1;

GRANT ALTER ANY TABLE TO &1;
GRANT ALTER ANY TABLE TO &1;
GRANT ALTER ANY PROCEDURE TO &1;
GRANT ALTER ANY TRIGGER TO &1;

GRANT DEBUG CONNECT SESSION TO &1;

GRANT ALTER SESSION TO &1;


EXIT SQL.SQLCODE
